# Generated by Django 4.2.4 on 2023-08-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
                (
                    "using_for",
                    models.CharField(
                        choices=[
                            ("phone_verification", "Phone Verification"),
                            ("email_verification", "Email Verification"),
                            ("password_reset", "Password Reset"),
                            (
                                "two_factor_authentication_login",
                                "Two Factor Authentication Login",
                            ),
                            (
                                "two_factor_authentication_update",
                                "Two Factor Authentication Update",
                            ),
                            ("no_request", "No Request"),
                        ],
                        default="no_request",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Email Verification",
            },
        ),
        migrations.CreateModel(
            name="PhoneVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verifying_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("otp", models.CharField(max_length=6)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
                (
                    "using_for",
                    models.CharField(
                        choices=[
                            ("phone_verification", "Phone Verification"),
                            ("email_verification", "Email Verification"),
                            ("password_reset", "Password Reset"),
                            (
                                "two_factor_authentication_login",
                                "Two Factor Authentication Login",
                            ),
                            (
                                "two_factor_authentication_update",
                                "Two Factor Authentication Update",
                            ),
                            ("no_request", "No Request"),
                        ],
                        default="no_request",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Phone Verification",
            },
        ),
    ]
